### PR TITLE
Fixes README links

### PR DESCRIPTION
**Pull request by stockiNail**
Fixes broken links in README.

The links are now addressing the class definitions.

### CODE REVIEW

**Comment by sgratzl** [comment]
thx

**Comment by stockiNail** [comment]
> 
> 
> thx

You are welcome! FYI, I'm going to include the controllers to [Charba project](https://pepstock-org.github.io/Charba-Wiki/), if you don't have any issue

**Comment by sgratzl** [comment]
sure it is a public/open source plugin for chart.js. You might be interested in one of my related plugins (https://github.com/sgratzl/chartjs-chart-geo#related-plugins) for chart.js, too

**Comment by stockiNail** [comment]
I have seen them and I'm evaluating. The geo chart is quite used in other charts lib and now I'm thinking only about that. I don't want to create many dependencies (and it's time consuming because I need to create a wrapper in java) .... But I see also graph could be interesting. Thank you for your work!

**Comment by stockiNail** [comment]
@sgratzl just FYI

Screenshot 2021-06-24 120524

**Pull request merged**
